[db]
addr = "root:root7944@tcp(127.0.0.1:3306)/fshop?charset=utf8mb4&parseTime=True&loc=Local"
max_open_conns = 16
max_idle_conns = 8
conn_max_life_time = 300

[redis]
#地址
addr = "127.0.0.1:6379"
#密码
password = ""
#redis 库
db = 0
#重试次数, 默认不重试
max_retries = 0
#连接池大小
pool_size = 32
#读取超时时间 3秒
read_timeout = 3
#写入超时时间 3秒
write_timeout = 3
#连接空闲时间 300秒
conn_max_idle_time = 300
#连接最长时间，1800秒
conn_max_life_time = 1800
#如果连接池已满 等待可用连接的时间默认 8秒
pool_timeout = 8

[other]
listen_addr = ":8000"
service_name = "fshop"
repository_request_timeout = 5
prometheus_listen_addr = ":9090"
# "fatal" "error" "warn" "info"  "debug"
logger_level = "debug"